#!/usr/bin/env bash
set -euo pipefail

tag="${TAG:?set TAG to the release tag, for example v0.1.0}"
tap_dir="${TAP_DIR:?set TAP_DIR to the cloned homebrew tap path}"
dist_dir="${DIST_DIR:-dist}"
version="${tag#v}"

checksum() {
  local file="$1"
  local sum
  sum="$(awk -v file="$file" '$2 == file { print $1 }' "$dist_dir/checksums.txt")"
  if [[ -z "$sum" ]]; then
    echo "missing checksum for $file" >&2
    exit 1
  fi
  printf '%s' "$sum"
}

darwin_amd64="paw_${version}_darwin_amd64.tar.gz"
darwin_arm64="paw_${version}_darwin_arm64.tar.gz"
linux_amd64="paw_${version}_linux_amd64.tar.gz"
linux_arm64="paw_${version}_linux_arm64.tar.gz"

mkdir -p "$tap_dir/Formula"
cat > "$tap_dir/Formula/paw.rb" <<FORMULA
# This file was generated by paw's release workflow. DO NOT EDIT.
class Paw < Formula
  desc "Go CLI coding-agent harness with validated context compression."
  homepage "https://github.com/gongahkia/paw-cli"
  version "$version"
  license "Apache-2.0"

  on_macos do
    on_intel do
      url "https://github.com/gongahkia/paw-cli/releases/download/v#{version}/$darwin_amd64"
      sha256 "$(checksum "$darwin_amd64")"
    end

    on_arm do
      url "https://github.com/gongahkia/paw-cli/releases/download/v#{version}/$darwin_arm64"
      sha256 "$(checksum "$darwin_arm64")"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/gongahkia/paw-cli/releases/download/v#{version}/$linux_amd64"
      sha256 "$(checksum "$linux_amd64")"
    end

    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/gongahkia/paw-cli/releases/download/v#{version}/$linux_arm64"
        sha256 "$(checksum "$linux_arm64")"
      end
    end
  end

  def install
    bin.install "paw"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/paw version")
  end
end
FORMULA
