package reviewweb

// reviewPage intentionally contains no interpolation except its CSP nonce and
// title. Source code from the reviewed worktree is always assigned through
// textContent in the script below; it is never parsed as browser markup.
const reviewPage = `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{{title}}</title>
<style nonce="{{nonce}}">
:root{color-scheme:dark;--bg:#171717;--panel:#242424;--line:#3d3d3d;--ink:#efefef;--muted:#a7a7a7;--pink:#ff7ac6;--green:#94d36a;--red:#ff7b7b;--blue:#94ceff}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--ink);font:14px/1.4 ui-monospace,SFMono-Regular,Menlo,monospace}header{position:sticky;top:0;background:#1d1d1d;border-bottom:1px solid var(--line);padding:14px 20px;z-index:2}h1{margin:0;color:var(--pink);font-size:18px}small,p{color:var(--muted)}button{font:inherit;color:var(--ink);background:#303030;border:1px solid #555;border-radius:5px;padding:6px 9px;cursor:pointer}button:hover,button:focus{border-color:var(--blue);outline:none}.selected{border-color:var(--pink);color:var(--pink)}main{padding:16px 20px;max-width:1700px;margin:auto}.summary{display:flex;gap:12px;align-items:center;flex-wrap:wrap;margin-bottom:14px}.summary strong{color:var(--blue)}.grid{display:grid;grid-template-columns:minmax(240px,30%) 1fr;gap:14px}.panel{background:var(--panel);border:1px solid var(--line);border-radius:7px;overflow:hidden}.panel h2{font-size:13px;margin:0;padding:10px 12px;border-bottom:1px solid var(--line);color:var(--pink)}.list{max-height:68vh;overflow:auto}.row{display:block;width:100%;border:0;border-bottom:1px solid #343434;border-radius:0;text-align:left;padding:9px 12px;background:transparent}.row .stats{float:right;color:var(--muted)}.row.active{background:#332a32;color:#fff}.detail{padding:12px}.hunks{display:flex;gap:6px;flex-wrap:wrap;margin-bottom:10px}.hunks button{max-width:100%;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.diff{margin:0;overflow:auto;max-height:50vh;border:1px solid #383838;background:#1b1b1b;padding:8px;white-space:pre}.diff div{min-height:1.4em}.add{color:var(--green)}.del{color:var(--red)}.meta{color:var(--blue)}.line{cursor:pointer}.line.range{background:#3a3540}.line.cursor{outline:1px solid var(--pink)}.controls{display:flex;gap:8px;flex-wrap:wrap;margin:12px 0}.request{border-top:1px solid var(--line);padding-top:12px}.request textarea{width:100%;min-height:80px;background:#181818;color:var(--ink);border:1px solid #555;border-radius:5px;padding:8px;font:inherit}.notice{min-height:1.4em;color:var(--muted)}.error{color:var(--red)}.success{color:var(--green)}.followup{white-space:pre-wrap;border:1px solid #555;padding:8px;border-radius:5px;color:var(--ink)}@media(max-width:760px){main{padding:10px}.grid{grid-template-columns:1fr}.list{max-height:28vh}.diff{max-height:38vh}}
</style></head><body><header><h1>Gator review</h1><small>Local retained-worktree review. This page is loopback-only and does not expose Gator RPC.</small></header><main>
<div class="summary"><strong id="summary">Loading review…</strong><span id="tabs"></span></div><div id="notice" class="notice"></div><div class="grid"><section class="panel"><h2>Files</h2><div id="files" class="list"></div></section><section class="panel"><h2 id="detail-title">Change</h2><div class="detail"><div id="hunks" class="hunks"></div><div id="diff" class="diff" tabindex="0"></div><div class="controls"><button id="toggle-raw">Raw file patch</button><button id="stage">Stage selected hunk</button><button id="stage-file">Stage file</button><button id="refresh">Refresh</button></div><div class="request"><label for="instruction">Request a range-scoped change</label><textarea id="instruction" maxlength="12288" placeholder="Select one or more focused diff lines, then describe the requested change."></textarea><div class="controls"><button id="send">Save change request</button><button id="clear-range">Clear range</button></div><div id="follow-up"></div></div></div></section></div>
</main><script nonce="{{nonce}}">
(() => {
  const $ = id => document.getElementById(id);
  const state = { snapshot:null, scope:'all', file:0, hunk:0, start:-1, end:-1, raw:false, patch:'' };
  const notice = (text, kind='') => { const n=$('notice'); n.textContent=text; n.className='notice '+kind; };
  const api = async (path, options={}) => { const r=await fetch(path,{credentials:'same-origin',...options}); const data=await r.json().catch(()=>({error:'Invalid server response'})); if(!r.ok) throw new Error(data.error||'Review request failed'); return data; };
  const set = () => state.snapshot ? state.snapshot[state.scope] : {files:[],stats:{}};
  const file = () => set().files[state.file];
  const hunk = () => { const f=file(); return f && f.hunks[state.hunk]; };
  const changed = () => { const s=set().stats||{}; return (s.files||0)+' files · '+(s.additions||0)+' additions · '+(s.deletions||0)+' deletions'; };
  const resetSelection = () => { state.file=0; state.hunk=0; state.start=-1; state.end=-1; state.raw=false; state.patch=''; };
  const append = (parent, tag, text, cls='') => { const el=document.createElement(tag); el.textContent=text; if(cls) el.className=cls; parent.append(el); return el; };
  const lineClass = line => line.kind==='addition'?'add':line.kind==='deletion'?'del':line.kind==='meta'?'meta':'';
  const selected = i => state.start>=0 && state.end>=0 && i>=Math.min(state.start,state.end) && i<=Math.max(state.start,state.end);
  function render() {
    const s=set(), f=file(), h=hunk();
    $('summary').textContent=(state.scope==='all'?'All changes':state.scope[0].toUpperCase()+state.scope.slice(1))+' · '+changed();
    $('tabs').replaceChildren(); ['all','unstaged','staged'].forEach(scope => { const b=append($('tabs'),'button',scope); if(scope===state.scope)b.classList.add('selected'); b.onclick=()=>{state.scope=scope;resetSelection();render();}; });
    $('files').replaceChildren(); (s.files||[]).forEach((item,i)=>{ const b=append($('files'),'button',item.path+'  +'+item.stats.additions+' −'+item.stats.deletions,'row'+(i===state.file?' active':'')); b.onclick=()=>{state.file=i;state.hunk=0;state.start=-1;state.end=-1;state.raw=false;state.patch='';render();}; });
    $('detail-title').textContent=f ? f.path+' · '+f.status : 'Change'; $('hunks').replaceChildren(); $('diff').replaceChildren(); $('follow-up').replaceChildren();
    if(!f){ append($('diff'),'div','No changed files in this scope.','meta'); buttons(); return; }
    (f.hunks||[]).forEach((item,i)=>{ const b=append($('hunks'),'button','Hunk '+(i+1)+' · +'+item.stats.additions+' −'+item.stats.deletions); if(i===state.hunk)b.classList.add('selected'); b.onclick=()=>{state.hunk=i;state.start=-1;state.end=-1;state.raw=false;render();}; });
    if(state.raw){ (state.patch||'Loading raw patch…').split('\n').forEach(row=>append($('diff'),'div',row,lineClass({kind:row[0]==='+'?'addition':row[0]==='-'?'deletion':row.startsWith('@@')?'meta':''}))); } else if(h){ append($('diff'),'div',h.header,'meta'); h.lines.forEach((line,i)=>{ const d=append($('diff'),'div',line.text,lineClass(line)+' line'+(selected(i)?' range':'')+(i===state.end?' cursor':'')); if(line.kind!=='meta')d.onclick=()=>{ if(state.start<0){state.start=i;state.end=i;}else{state.end=i;}render();}; }); } else append($('diff'),'div','Binary or metadata-only change. Use the whole-file control.','meta');
    buttons();
  }
  function buttons(){ const mutable=state.scope!=='all', f=file(), h=hunk(); $('toggle-raw').disabled=!f; $('toggle-raw').textContent=state.raw?'Focused selected hunk':'Raw file patch'; $('stage').disabled=!mutable||!h; $('stage-file').disabled=!mutable||!f; const verb=state.scope==='staged'?'Unstage':'Stage'; $('stage').textContent=verb+' selected hunk'; $('stage-file').textContent=verb+' file'; }
  async function refresh(){ try { state.snapshot=await api('/review/api/snapshot'); resetSelection(); notice('Review refreshed.','success'); render(); } catch(e){notice(e.message,'error');} }
  async function raw(){ const f=file(); if(!f)return; try { state.raw=!state.raw; if(state.raw&&!state.patch){const data=await api('/review/api/file?id='+encodeURIComponent(f.id)+'&scope='+encodeURIComponent(state.scope));state.patch=data.patch;} render(); } catch(e){state.raw=false;notice(e.message,'error');} }
  async function stage(whole){ const f=file(), h=hunk(); if(!f||(!whole&&!h))return; const verb=state.scope==='staged'?'unstage':'stage'; if(!confirm('Explicitly '+verb+' '+(whole?'this file':'this hunk')+' in Gator’s retained worktree?'))return; try { state.snapshot=await api('/review/api/stage',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({scope:state.scope,file_id:f.id,hunk_id:h&&h.id,whole})}); resetSelection(); notice('Review selection updated in the retained worktree.','success'); render(); } catch(e){notice(e.message,'error');} }
  async function feedback(){ const f=file(), h=hunk(); if(!f||!h||state.start<0||state.end<0){notice('Select a contiguous focused diff range first.','error');return;} const instruction=$('instruction').value.trim(); if(!instruction){notice('Describe the requested change first.','error');return;} try { const data=await api('/review/api/feedback',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({scope:state.scope,file_id:f.id,hunk_id:h.id,start:Math.min(state.start,state.end),end:Math.max(state.start,state.end),instruction})}); const out=append($('follow-up'),'pre',data.follow_up,'followup'); const copy=append($('follow-up'),'button','Copy constrained follow-up'); copy.onclick=()=>navigator.clipboard&&navigator.clipboard.writeText(out.textContent).then(()=>notice('Follow-up copied. Resume this retained Gator thread to send it.','success')).catch(()=>notice('Copy is unavailable; select the displayed follow-up text.','error')); $('instruction').value=''; notice('Range-scoped request saved privately beside the retained run.','success'); } catch(e){notice(e.message,'error');} }
  $('toggle-raw').onclick=raw; $('stage').onclick=()=>stage(false); $('stage-file').onclick=()=>stage(true); $('refresh').onclick=refresh; $('send').onclick=feedback; $('clear-range').onclick=()=>{state.start=-1;state.end=-1;render();};
  document.addEventListener('keydown',event=>{ if(event.target.tagName==='TEXTAREA')return; if(['1','2','3'].includes(event.key)){state.scope={1:'all',2:'unstaged',3:'staged'}[event.key];resetSelection();render();} else if(event.key==='ArrowDown'||event.key==='j'){state.file=Math.min(state.file+1,Math.max(0,set().files.length-1));state.hunk=0;render();} else if(event.key==='ArrowUp'||event.key==='k'){state.file=Math.max(0,state.file-1);state.hunk=0;render();} else if(event.key==='f'){raw();} else if(event.key==='v'){const h=hunk();if(h){state.start=0;state.end=0;render();}} else if(event.key==='r'){$('instruction').focus();} });
  refresh();
})();
</script></body></html>`
