package engine

import (
	_ "embed"
	"encoding/json"
	"fmt"
	"path/filepath"

	"github.com/gongahkia/norbot/internal/config"
	"github.com/gongahkia/norbot/internal/domain"
	"github.com/gongahkia/norbot/internal/runtime"
)

//go:embed assets/frontend/package-lock.json
var frontendLockfile string

func generateApp(workspace runtime.ArtifactWorkspace, run domain.Run, toolPolicy map[string]config.ToolPolicy) ([]string, error) {
	files := map[string]string{
		"generated-app/README.md":                           fmt.Sprintf("# Generated by Norbot\n\nRun: `%s`\nProfile: `%s`\n\nThis project was generated from an operator-approved graph.\n", run.ID, run.Profile),
		"generated-app/frontend/package.json":               `{"name":"generated-frontend","private":true,"version":"0.1.0","scripts":{"dev":"vite --host 0.0.0.0","build":"vite build","test":"node --test tests/*.test.mjs"},"dependencies":{"@vitejs/plugin-react":"6.0.4","vite":"8.1.5","react":"19.2.8","react-dom":"19.2.8"},"devDependencies":{}}`,
		"generated-app/frontend/index.html":                 `<div id="root"></div><script type="module" src="/src/main.jsx"></script>`,
		"generated-app/frontend/src/main.jsx":               `import {createRoot} from "react-dom/client"; import React from "react"; import "./style.css"; const App=()=> <main><h1>Norbot generated app</h1><p>Operator-approved app scaffold.</p></main>; createRoot(document.getElementById("root")).render(<App/>);`,
		"generated-app/frontend/src/style.css":              `:root{font-family:ui-sans-serif,system-ui;color:#172033;background:#f7f8fb}body{margin:0}main{max-width:48rem;margin:4rem auto;padding:2rem;background:#fff;border:1px solid #dce1ea;border-radius:.5rem}h1{margin-top:0}`,
		"generated-app/frontend/Dockerfile":                 "FROM node:22-alpine AS build\nWORKDIR /app\nCOPY package.json package-lock.json ./\nRUN npm ci\nCOPY . .\nRUN npm run build\nFROM nginx:1.27-alpine\nCOPY --from=build /app/dist /usr/share/nginx/html\nEXPOSE 80\n",
		"generated-app/kubernetes/README.md":                "# Kubernetes artifacts\n\nNorbot applies equivalent client-go resources at deployment time. These portable manifests document the generated workload shape.\n",
		"generated-app/kubernetes/kustomization.yaml":       "apiVersion: kustomize.config.k8s.io/v1beta1\nkind: Kustomization\nresources:\n- frontend-deployment.yaml\n- frontend-service.yaml\n",
		"generated-app/kubernetes/frontend-deployment.yaml": "apiVersion: apps/v1\nkind: Deployment\nmetadata:\n  name: generated-frontend\nspec:\n  replicas: 1\n  selector:\n    matchLabels:\n      app: generated-frontend\n  template:\n    metadata:\n      labels:\n        app: generated-frontend\n    spec:\n      containers:\n      - name: frontend\n        image: REPLACE_WITH_FRONTEND_IMAGE\n        ports:\n        - containerPort: 80\n        readinessProbe:\n          httpGet: {path: /, port: 80}\n",
		"generated-app/kubernetes/frontend-service.yaml":    "apiVersion: v1\nkind: Service\nmetadata:\n  name: generated-frontend\nspec:\n  type: ClusterIP\n  selector:\n    app: generated-frontend\n  ports:\n  - port: 80\n    targetPort: 80\n",
		"generated-app/frontend/tests/app.test.mjs":         `import test from "node:test"; import assert from "node:assert/strict"; test("generated app contract",()=>assert.equal("Norbot".length,6));`,
		"generated-app/frontend/package-lock.json":          frontendLockfile,
	}
	if run.Profile != domain.ProfileFrontend {
		files["generated-app/kubernetes/backend-deployment.yaml"] = "apiVersion: apps/v1\nkind: Deployment\nmetadata:\n  name: generated-backend\nspec:\n  replicas: 1\n  selector:\n    matchLabels:\n      app: generated-backend\n  template:\n    metadata:\n      labels:\n        app: generated-backend\n    spec:\n      containers:\n      - name: backend\n        image: REPLACE_WITH_BACKEND_IMAGE\n        ports:\n        - containerPort: 8000\n        readinessProbe:\n          httpGet: {path: /api/health, port: 8000}\n"
		files["generated-app/kubernetes/backend-service.yaml"] = "apiVersion: v1\nkind: Service\nmetadata:\n  name: generated-backend\nspec:\n  type: ClusterIP\n  selector:\n    app: generated-backend\n  ports:\n  - port: 8000\n    targetPort: 8000\n"
		files["generated-app/kubernetes/kustomization.yaml"] = "apiVersion: kustomize.config.k8s.io/v1beta1\nkind: Kustomization\nresources:\n- frontend-deployment.yaml\n- frontend-service.yaml\n- backend-deployment.yaml\n- backend-service.yaml\n"
		files["generated-app/backend/go.mod"] = "module generated/backend\n\ngo 1.26.0\n"
		files["generated-app/backend/go.sum"] = ""
		files["generated-app/backend/main.go"] = `package main
import("fmt";"log";"net/http";"os")
func main(){http.HandleFunc("/api/health",func(w http.ResponseWriter,r *http.Request){w.Header().Set("content-type","application/json");fmt.Fprint(w,` + "`{\"status\":\"ok\"}`" + `)});port:=os.Getenv("PORT");if port==""{port="8000"};log.Fatal(http.ListenAndServe(":"+port,nil))}`
		files["generated-app/backend/Dockerfile"] = "FROM golang:1.26-alpine AS build\nWORKDIR /app\nCOPY . .\nRUN go build -o server .\nFROM alpine:3.21\nCOPY --from=build /app/server /server\nEXPOSE 8000\nCMD [\"/server\"]\n"
		compose := `services:
  backend:
    build: ./backend
    environment: ["PORT=8000"]
    healthcheck:
      test: ["CMD", "wget", "-q", "-O", "-", "http://127.0.0.1:8000/api/health"]
      interval: 5s
      timeout: 3s
      retries: 12
  frontend:
    build: ./frontend
    ports: ["${NORBOT_PUBLIC_PORT}:80"]
    depends_on:
      backend:
        condition: service_healthy
`
		if run.Profile == domain.ProfileAgentic {
			compose = `services:
  backend:
    build: ./backend
    volumes: ["agent_state:/var/lib/app"]
    environment: ["PORT=8000", "AGENT_STATE_PATH=/var/lib/app/agent.db", "AGENT_TOOL_POLICY_PATH=/app/tool_policy.json"]
    healthcheck:
      test: ["CMD", "wget", "-q", "-O", "-", "http://127.0.0.1:8000/api/health"]
      interval: 5s
      timeout: 3s
      retries: 12
  frontend:
    build: ./frontend
    ports: ["${NORBOT_PUBLIC_PORT}:80"]
    depends_on:
      backend:
        condition: service_healthy
volumes:
  agent_state:
`
		}
		files["generated-app/docker-compose.yml"] = compose
	} else {
		files["generated-app/docker-compose.yml"] = `services:
  frontend:
    build: ./frontend
    ports: ["${NORBOT_PUBLIC_PORT}:80"]
`
	}
	if run.Profile == domain.ProfileAgentic {
		encodedPolicy, err := json.Marshal(toolPolicy)
		if err != nil {
			return nil, err
		}
		files["generated-app/backend/go.mod"] = agentGoMod
		files["generated-app/backend/go.sum"] = agentGoSum
		files["generated-app/backend/main.go"] = agentMainSource
		files["generated-app/backend/harness.go"] = agentHarnessSource
		files["generated-app/backend/tool_policy.json"] = string(encodedPolicy)
		files["generated-app/backend/harness_test.go"] = agentHarnessTestSource
		files["generated-app/backend/APPROVALS.md"] = "# App-local action approvals\n\nConsequential tool invocations enter this app's persistent approval queue. The app operator approves or rejects each action before execution. Norbot does not broker runtime tool approvals.\n"
	}
	paths := make([]string, 0, len(files))
	for relative, content := range files {
		if _, err := workspace.WriteArtifact(run.ID, relative, []byte(content)); err != nil {
			return nil, err
		}
		paths = append(paths, filepath.ToSlash(relative))
	}
	return paths, nil
}

const agentGoMod = `module generated/backend

go 1.26.0

require (
	github.com/dustin/go-humanize v1.0.1 // indirect
	github.com/google/uuid v1.6.0 // indirect
	github.com/mattn/go-isatty v0.0.20 // indirect
	github.com/ncruces/go-strftime v1.0.0 // indirect
	github.com/remyoudompheng/bigfft v0.0.0-20230129092748-24d4a6f8daec // indirect
	golang.org/x/sys v0.46.0 // indirect
	modernc.org/libc v1.74.1 // indirect
	modernc.org/mathutil v1.7.1 // indirect
	modernc.org/memory v1.11.0 // indirect
	modernc.org/sqlite v1.54.0
)
`

const agentGoSum = `github.com/dustin/go-humanize v1.0.1 h1:GzkhY7T5VNhEkwH0PVJgjz+fX1rhBrR7pRT3mDkpeCY=
github.com/dustin/go-humanize v1.0.1/go.mod h1:Mu1zIs6XwVuF/gI1OepvI0qD18qycQx+mFykh5fBlto=
github.com/google/uuid v1.6.0 h1:NIvaJDMOsjHA8n1jAhLSgzrAzy1Hgr+hNrb57e+94F0=
github.com/google/uuid v1.6.0/go.mod h1:TIyPZe4MgqvfeYDBFedMoGGpEw/LqOeaOT+nhxU+yHo=
github.com/mattn/go-isatty v0.0.20 h1:xfD0iDuEKnDkl03q4limB+vH+GxLEtL/jb4xVJSWWEY=
github.com/mattn/go-isatty v0.0.20/go.mod h1:W+V8PltTTMOvKvAeJH7IuucS94S2C6jfK/D7dTCTo3Y=
github.com/ncruces/go-strftime v1.0.0 h1:HMFp8mLCTPp341M/ZnA4qaf7ZlsbTc+miZjCLOFAw7w=
github.com/ncruces/go-strftime v1.0.0/go.mod h1:Fwc5htZGVVkseilnfgOVb9mKy6w1naJmn9CehxcKcls=
github.com/remyoudompheng/bigfft v0.0.0-20230129092748-24d4a6f8daec h1:W09IVJc94icq4NjY3clb7Lk8O1qJ8BdBEF8z0ibU0rE=
github.com/remyoudompheng/bigfft v0.0.0-20230129092748-24d4a6f8daec/go.mod h1:qqbHyh8v60DhA7CoWK5oRCqLrMHRGoxYCSS9EjAz6Eo=
golang.org/x/sys v0.6.0/go.mod h1:oPkhp1MJrh7nUepCBck5+mAzfO9JrbApNNgaTdGDITg=
golang.org/x/sys v0.46.0 h1:noSf2Fq6F8DBgS+LysIkx7rIExoNHJsxOAtPp4rthXw=
golang.org/x/sys v0.46.0/go.mod h1:4GL1E5IUh+htKOUEOaiffhrAeqysfVGipDYzABqnCmw=
modernc.org/libc v1.74.1 h1:bdR4VTKFMC4966QSNZ05XLGI/VwzVa2kTUX51Dm0riQ=
modernc.org/libc v1.74.1/go.mod h1:uH4t5bOx3G3g9Xcmj10YKlTcVISlRDwv8VoQJG9n8Os=
modernc.org/mathutil v1.7.1 h1:GCZVGXdaN8gTqB1Mf/usp1Y/hSqgI2vAGGP4jZMCxOU=
modernc.org/mathutil v1.7.1/go.mod h1:4p5IwJITfppl0G4sUEDtCr4DthTaT47/N3aT6MhfgJg=
modernc.org/memory v1.11.0 h1:o4QC8aMQzmcwCK3t3Ux/ZHmwFPzE6hf2Y5LbkRs+hbI=
modernc.org/memory v1.11.0/go.mod h1:/JP4VbVC+K5sU2wZi9bHoq2MAkCnrt2r98UGeSK7Mjw=
modernc.org/sqlite v1.54.0 h1:JCxR4qwkJvOaqAoYcgDoO25Nc+ROg6EJ2LfBVzdrgog=
modernc.org/sqlite v1.54.0/go.mod h1:4ntCLuNmnH8+GNqjka1wNg7KJd5/Hi5FYp8K+XQ7GZw=
`

const agentMainSource = `package main

import ("log";"net/http";"os")
func main(){app,err:=NewAgentApp(os.Getenv("AGENT_STATE_PATH"));if err!=nil{log.Fatal(err)};port:=os.Getenv("PORT");if port==""{port="8000"};log.Fatal(http.ListenAndServe(":"+port,app.Handler()))}
`

const agentHarnessTestSource = `package main

import("bytes";"encoding/json";"net/http";"net/http/httptest";"path/filepath";"testing")
func TestApprovalIsPersistentAndSingleUse(t *testing.T){app,err:=NewAgentApp(filepath.Join(t.TempDir(),"agent.db"));if err!=nil{t.Fatal(err)};defer app.db.Close();defer app.appDB.Close();body:=[]byte("{\"role\":\"operator\",\"tool\":\"database_mutate\",\"params\":{\"statement\":\"UPDATE actions SET status=status WHERE 1=0\"}}");request:=httptest.NewRequest(http.MethodPost,"/api/actions",bytes.NewReader(body));response:=httptest.NewRecorder();app.Handler().ServeHTTP(response,request);if response.Code!=http.StatusAccepted{t.Fatalf("status=%d body=%s",response.Code,response.Body.String())};var action Action;if err:=json.NewDecoder(response.Body).Decode(&action);err!=nil{t.Fatal(err)};approve:=httptest.NewRequest(http.MethodPost,"/api/approvals/"+action.ID+"/approve",nil);approved:=httptest.NewRecorder();app.Handler().ServeHTTP(approved,approve);if approved.Code!=http.StatusOK{t.Fatalf("status=%d body=%s",approved.Code,approved.Body.String())};again:=httptest.NewRecorder();app.Handler().ServeHTTP(again,approve);if again.Code!=http.StatusConflict{t.Fatalf("status=%d",again.Code)}}
`

const agentHarnessSource = `package main

import (
	"bytes"
	"context"
 "crypto/rand"
 "crypto/sha256"
 "database/sql"
 "encoding/hex"
 "encoding/json"
 "errors"
 "fmt"
 "io"
 "net/http"
 "net/url"
 "os"
 "os/exec"
 "path/filepath"
 "strings"
 "time"
 _ "modernc.org/sqlite"
)

const maxTurns=5
const maxToolCalls=10
const maxRunDuration=10*time.Minute
type ToolSpec struct{Name string ` + "`json:\"name\"`" + `; Roles []string ` + "`json:\"roles\"`" + `; ApprovalRequired bool ` + "`json:\"approval_required\"`" + `; Enabled bool ` + "`json:\"enabled\"`" + `; AllowedHosts []string ` + "`json:\"allowed_hosts,omitempty\"`" + `; AllowedCommands []string ` + "`json:\"allowed_commands,omitempty\"`" + `}
type ToolPolicy struct{Enabled bool ` + "`json:\"enabled\"`" + `;ApprovalRequired bool ` + "`json:\"approval_required\"`" + `;Roles []string ` + "`json:\"roles\"`" + `;AllowedHosts []string ` + "`json:\"allowed_hosts\"`" + `;AllowedCommands []string ` + "`json:\"allowed_commands\"`" + `}
type Action struct{ID string ` + "`json:\"id\"`" + `;Tool string ` + "`json:\"tool\"`" + `;Role string ` + "`json:\"role\"`" + `;Params map[string]any ` + "`json:\"params\"`" + `;Digest string ` + "`json:\"digest\"`" + `;Status string ` + "`json:\"status\"`" + `;ExpiresAt time.Time ` + "`json:\"expires_at\"`" + `;Result any ` + "`json:\"result,omitempty\"`" + `;CreatedAt time.Time ` + "`json:\"created_at\"`" + `}
type ToolCall struct{Tool string ` + "`json:\"tool\"`" + `;Params map[string]any ` + "`json:\"params\"`" + `}
type Provider struct{Kind string ` + "`json:\"kind\"`" + `;BaseURL string ` + "`json:\"base_url\"`" + `;Model string ` + "`json:\"model\"`" + `;CredentialEnv string ` + "`json:\"credential_env\"`" + `}
type AgentRequest struct{SessionID string ` + "`json:\"session_id\"`" + `;ExternalID string ` + "`json:\"external_id\"`" + `;IdempotencyKey string ` + "`json:\"idempotency_key\"`" + `;Role string ` + "`json:\"role\"`" + `;Prompt string ` + "`json:\"prompt\"`" + `;Attachments []map[string]any ` + "`json:\"attachments\"`" + `;Provider Provider ` + "`json:\"provider\"`" + `}
type App struct{db *sql.DB;appDB *sql.DB;root string;tools map[string]ToolSpec;http *http.Client}

func NewAgentApp(path string)(*App,error){if path==""{path="agent.db"};if err:=os.MkdirAll(filepath.Dir(path),0o750);err!=nil{return nil,err};db,err:=sql.Open("sqlite",path+"?_pragma=busy_timeout(5000)&_pragma=journal_mode(WAL)");if err!=nil{return nil,err};applicationPath:=env("AGENT_APPLICATION_DB_PATH",filepath.Join(filepath.Dir(path),"application.db"));appDB,err:=sql.Open("sqlite",applicationPath+"?_pragma=busy_timeout(5000)&_pragma=journal_mode(WAL)");if err!=nil{db.Close();return nil,err};a:=&App{db:db,appDB:appDB,root:env("AGENT_ARTIFACT_ROOT","/app/artifacts"),http:&http.Client{Timeout:30*time.Second}};a.tools=defaultTools();if err:=a.applyPolicy();err!=nil{db.Close();appDB.Close();return nil,err};if err:=a.migrate();err!=nil{db.Close();appDB.Close();return nil,err};return a,nil}
func env(key,fallback string)string{if value:=strings.TrimSpace(os.Getenv(key));value!=""{return value};return fallback}
func defaultTools()map[string]ToolSpec{return map[string]ToolSpec{
 "artifact_read":{Name:"artifact_read",Roles:[]string{"researcher","builder","operator"},Enabled:true},
 "http_get":{Name:"http_get",Roles:[]string{"researcher","operator"},Enabled:true},
 "http_write":{Name:"http_write",Roles:[]string{"operator"},Enabled:true,ApprovalRequired:true},
 "database_mutate":{Name:"database_mutate",Roles:[]string{"operator"},Enabled:true,ApprovalRequired:true},
 "shell":{Name:"shell",Roles:[]string{"operator"},Enabled:env("AGENT_ENABLE_SHELL","false")=="true",ApprovalRequired:true},
 }}
func(a *App)applyPolicy()error{path:=strings.TrimSpace(os.Getenv("AGENT_TOOL_POLICY_PATH"));if path==""{return nil};data,err:=os.ReadFile(path);if err!=nil{return err};policies:=map[string]ToolPolicy{};if err:=json.Unmarshal(data,&policies);err!=nil{return err};for name,spec:=range a.tools{spec.Enabled=false;a.tools[name]=spec};for name,policy:=range policies{spec,ok:=a.tools[name];if !ok{return fmt.Errorf("unknown tool policy %q",name)};spec.Enabled=policy.Enabled;spec.ApprovalRequired=policy.ApprovalRequired;spec.Roles=policy.Roles;spec.AllowedHosts=policy.AllowedHosts;spec.AllowedCommands=policy.AllowedCommands;a.tools[name]=spec};return nil}
func(a *App)migrate()error{_,err:=a.db.Exec(` + "`" + `CREATE TABLE IF NOT EXISTS actions(id TEXT PRIMARY KEY,tool TEXT NOT NULL,role TEXT NOT NULL,params TEXT NOT NULL,digest TEXT NOT NULL,status TEXT NOT NULL,expires_at TEXT NOT NULL,result TEXT NOT NULL DEFAULT '',created_at TEXT NOT NULL,updated_at TEXT NOT NULL);CREATE TABLE IF NOT EXISTS audit_events(id INTEGER PRIMARY KEY AUTOINCREMENT,event_type TEXT NOT NULL,action_id TEXT NOT NULL DEFAULT '',metadata TEXT NOT NULL,created_at TEXT NOT NULL);CREATE TABLE IF NOT EXISTS agent_sessions(id TEXT PRIMARY KEY,external_id TEXT NOT NULL,summary TEXT NOT NULL DEFAULT '',updated_at TEXT NOT NULL);CREATE TABLE IF NOT EXISTS agent_turns(idempotency_key TEXT PRIMARY KEY,session_id TEXT NOT NULL,response TEXT NOT NULL,created_at TEXT NOT NULL)` + "`" + `);return err}
func(a *App)Handler()http.Handler{mux:=http.NewServeMux();mux.HandleFunc("GET /api/health",a.health);mux.HandleFunc("GET /api/tools",a.listTools);mux.HandleFunc("GET /api/approvals",a.listApprovals);mux.HandleFunc("POST /api/actions",a.createAction);mux.HandleFunc("POST /api/approvals/{id}/approve",a.approve);mux.HandleFunc("POST /api/approvals/{id}/reject",a.reject);mux.HandleFunc("POST /api/agents/run",a.runAgentSession);return mux}
func(a *App)health(w http.ResponseWriter,r *http.Request){writeJSON(w,200,map[string]any{"status":"ok","approval_store":"sqlite"})}
func(a *App)listTools(w http.ResponseWriter,r *http.Request){values:=[]ToolSpec{};for _,tool:=range a.tools{values=append(values,tool)};writeJSON(w,200,values)}
func(a *App)createAction(w http.ResponseWriter,r *http.Request){var in struct{Role string ` + "`json:\"role\"`" + `;Tool string ` + "`json:\"tool\"`" + `;Params map[string]any ` + "`json:\"params\"`" + `};if err:=decode(r,&in);err!=nil{writeError(w,400,err);return};action,err:=a.submit(in.Role,in.Tool,in.Params);if err!=nil{writeError(w,422,err);return};status:=200;if action.Status=="pending"{status=202};writeJSON(w,status,action)}
func(a *App)listApprovals(w http.ResponseWriter,r *http.Request){rows,err:=a.db.QueryContext(r.Context(),"SELECT id,tool,role,params,digest,status,expires_at,result,created_at FROM actions WHERE status='pending' ORDER BY created_at");if err!=nil{writeError(w,500,err);return};defer rows.Close();items:=[]Action{};for rows.Next(){item,err:=scanAction(rows);if err!=nil{writeError(w,500,err);return};items=append(items,item)};writeJSON(w,200,items)}
func(a *App)approve(w http.ResponseWriter,r *http.Request){action,err:=a.transition(r.PathValue("id"),"approved");if err!=nil{writeError(w,409,err);return};result,err:=a.execute(action);if err!=nil{a.finish(action.ID,"failed",map[string]string{"error":err.Error()});writeError(w,422,err);return};if err:=a.finish(action.ID,"completed",result);err!=nil{writeError(w,500,err);return};action.Status="completed";action.Result=result;writeJSON(w,200,action)}
func(a *App)reject(w http.ResponseWriter,r *http.Request){action,err:=a.transition(r.PathValue("id"),"rejected");if err!=nil{writeError(w,409,err);return};writeJSON(w,200,action)}
func(a *App)submit(role,tool string,params map[string]any)(Action,error){spec,err:=a.validate(role,tool,params);if err!=nil{return Action{},err};encoded,err:=json.Marshal(params);if err!=nil{return Action{},err};digest:=sha256.Sum256(append([]byte(tool+"\n"+role+"\n"),encoded...));action:=Action{ID:newID(),Tool:tool,Role:role,Params:params,Digest:"sha256:"+hex.EncodeToString(digest[:]),Status:"pending",ExpiresAt:time.Now().UTC().Add(30*time.Minute),CreatedAt:time.Now().UTC()};if !spec.ApprovalRequired{result,err:=a.execute(action);if err!=nil{return Action{},err};action.Status="completed";action.Result=result};result,_:=json.Marshal(action.Result);_,err=a.db.Exec("INSERT INTO actions(id,tool,role,params,digest,status,expires_at,result,created_at,updated_at)VALUES(?,?,?,?,?,?,?,?,?,?)",action.ID,action.Tool,action.Role,string(encoded),action.Digest,action.Status,action.ExpiresAt.Format(time.RFC3339Nano),string(result),action.CreatedAt.Format(time.RFC3339Nano),action.CreatedAt.Format(time.RFC3339Nano));if err!=nil{return Action{},err};a.audit("action_"+action.Status,action.ID,map[string]any{"tool":tool,"role":role,"digest":action.Digest});return action,nil}
func(a *App)transition(id,status string)(Action,error){now:=time.Now().UTC();result,err:=a.db.Exec("UPDATE actions SET status=?,updated_at=? WHERE id=? AND status='pending' AND expires_at>?",status,now.Format(time.RFC3339Nano),id,now.Format(time.RFC3339Nano));if err!=nil{return Action{},err};if changed,_:=result.RowsAffected();changed!=1{return Action{},errors.New("approval is missing, expired, or already decided")};action,err:=a.action(id);if err==nil{a.audit("action_"+status,id,map[string]any{"digest":action.Digest})};return action,err}
func(a *App)finish(id,status string,result any)error{encoded,err:=json.Marshal(result);if err!=nil{return err};_,err=a.db.Exec("UPDATE actions SET status=?,result=?,updated_at=? WHERE id=?",status,string(encoded),time.Now().UTC().Format(time.RFC3339Nano),id);if err==nil{a.audit("action_"+status,id,nil)};return err}
func(a *App)action(id string)(Action,error){row:=a.db.QueryRow("SELECT id,tool,role,params,digest,status,expires_at,result,created_at FROM actions WHERE id=?",id);return scanAction(row)}
type scanner interface{Scan(...any)error}
func scanAction(row scanner)(Action,error){var item Action;var params,result,expires,created string;if err:=row.Scan(&item.ID,&item.Tool,&item.Role,&params,&item.Digest,&item.Status,&expires,&result,&created);err!=nil{return Action{},err};if err:=json.Unmarshal([]byte(params),&item.Params);err!=nil{return Action{},err};_ = json.Unmarshal([]byte(result),&item.Result);item.ExpiresAt,_=time.Parse(time.RFC3339Nano,expires);item.CreatedAt,_=time.Parse(time.RFC3339Nano,created);return item,nil}
func(a *App)validate(role,tool string,params map[string]any)(ToolSpec,error){spec,ok:=a.tools[tool];if !ok||!spec.Enabled{return ToolSpec{},fmt.Errorf("tool %q is not enabled",tool)};if !contains(spec.Roles,role){return ToolSpec{},fmt.Errorf("role %q cannot invoke %q",role,tool)};switch tool{case "artifact_read":path,ok:=params["path"].(string);if !ok||!safePath(path){return ToolSpec{},errors.New("artifact_read requires a safe relative path")};case "http_get","http_write":raw,ok:=params["url"].(string);if !ok{return ToolSpec{},errors.New("http tool requires url")};parsed,err:=url.Parse(raw);if err!=nil||parsed.Scheme!="https"||!allowedHost(parsed.Hostname(),spec.AllowedHosts){return ToolSpec{},errors.New("URL must use an allowlisted HTTPS host")};if tool=="http_write"{method,_:=params["method"].(string);if method!="POST"&&method!="PUT"&&method!="PATCH"{return ToolSpec{},errors.New("http_write supports POST, PUT, or PATCH")}};case "database_mutate":statement,ok:=params["statement"].(string);if !ok||!mutation(statement){return ToolSpec{},errors.New("database_mutate requires one INSERT, UPDATE, or DELETE statement")};case "shell":command,ok:=params["command"].(string);if !ok||!contains(spec.AllowedCommands,command){return ToolSpec{},errors.New("shell command is not allowlisted")}};return spec,nil}
func(a *App)execute(action Action)(any,error){switch action.Tool{case "artifact_read":data,err:=os.ReadFile(filepath.Join(a.root,action.Params["path"].(string)));if err!=nil{return nil,err};if len(data)>1<<20{return nil,errors.New("artifact exceeds 1 MiB")};return map[string]string{"content":string(data)},nil;case "http_get","http_write":method:=http.MethodGet;if action.Tool=="http_write"{method=action.Params["method"].(string)};var body io.Reader;if raw,ok:=action.Params["body"].(string);ok{body=strings.NewReader(raw)};request,err:=http.NewRequest(method,action.Params["url"].(string),body);if err!=nil{return nil,err};response,err:=a.http.Do(request);if err!=nil{return nil,err};defer response.Body.Close();data,err:=io.ReadAll(io.LimitReader(response.Body,1<<20));if err!=nil{return nil,err};return map[string]any{"status":response.StatusCode,"body":string(data)},nil;case "database_mutate":if _,err:=a.appDB.Exec("CREATE TABLE IF NOT EXISTS actions(status TEXT)");err!=nil{return nil,err};args,_:=action.Params["args"].([]any);result,err:=a.appDB.Exec(action.Params["statement"].(string),args...);if err!=nil{return nil,err};rows,_:=result.RowsAffected();return map[string]any{"rows_affected":rows},nil;case "shell":args:=[]string{};for _,raw:=range array(action.Params["args"]){value,ok:=raw.(string);if !ok{return nil,errors.New("shell args must be strings")};args=append(args,value)};ctx,cancel:=context.WithTimeout(context.Background(),30*time.Second);defer cancel();out,err:=exec.CommandContext(ctx,action.Params["command"].(string),args...).CombinedOutput();if err!=nil{return nil,fmt.Errorf("shell: %w: %s",err,string(out))};return map[string]string{"output":string(out)},nil};return nil,errors.New("unknown tool")}
func(a *App)audit(kind,id string,metadata map[string]any){encoded,_:=json.Marshal(metadata);_,_=a.db.Exec("INSERT INTO audit_events(event_type,action_id,metadata,created_at)VALUES(?,?,?,?)",kind,id,string(encoded),time.Now().UTC().Format(time.RFC3339Nano))}
func(a *App)runAgent(w http.ResponseWriter,r *http.Request){var request AgentRequest;if err:=decode(r,&request);err!=nil{writeError(w,400,err);return};if request.Role==""||request.Prompt==""{writeError(w,422,errors.New("role and prompt are required"));return};deadline:=time.Now().Add(maxRunDuration);calls:=0;history:=request.Prompt;outcomes:=[]any{};for turn:=0;turn<maxTurns&&time.Now().Before(deadline);turn++{text,err:=complete(r.Context(),a.http,request.Provider,history);if err!=nil{writeError(w,422,err);return};var plan struct{Final string ` + "`json:\"final\"`" + `;ToolCalls []ToolCall ` + "`json:\"tool_calls\"`" + `};if err:=json.Unmarshal(extractObject(text),&plan);err!=nil{writeError(w,422,fmt.Errorf("provider must return strict agent JSON: %w",err));return};if len(plan.ToolCalls)==0{writeJSON(w,200,map[string]any{"final":plan.Final,"outcomes":outcomes,"turns":turn+1});return};for _,call:=range plan.ToolCalls{calls++;if calls>maxToolCalls{writeError(w,422,errors.New("tool-call limit reached"));return};action,err:=a.submit(request.Role,call.Tool,call.Params);if err!=nil{writeError(w,422,err);return};outcomes=append(outcomes,action);if action.Status=="pending"{writeJSON(w,202,map[string]any{"status":"awaiting_approval","approval":action,"outcomes":outcomes});return}};encoded,_:=json.Marshal(outcomes);history=request.Prompt+"\nTool outcomes: "+string(encoded)};writeError(w,422,errors.New("agent turn limit reached"))}
func complete(ctx context.Context,client *http.Client,p Provider,prompt string)(string,error){key:=os.Getenv(p.CredentialEnv);if p.Kind==""||p.BaseURL==""||p.Model==""||key==""{return "",errors.New("provider kind, base URL, model, and credential env are required")};instruction:="Return strict JSON only: {\\\"final\\\":string,\\\"tool_calls\\\":[{\\\"tool\\\":string,\\\"params\\\":object}]}. Use only declared least-privilege tools.";var endpoint string;var body any;headers:=map[string]string{};switch p.Kind{case "openai_responses":endpoint=strings.TrimRight(p.BaseURL,"/")+"/responses";body=map[string]any{"model":p.Model,"input":instruction+"\n"+prompt};headers["Authorization"]="Bearer "+key;case "openai_compatible":endpoint=strings.TrimRight(p.BaseURL,"/")+"/chat/completions";body=map[string]any{"model":p.Model,"messages":[]map[string]string{{"role":"system","content":instruction},{"role":"user","content":prompt}}};headers["Authorization"]="Bearer "+key;case "anthropic_messages":endpoint=strings.TrimRight(p.BaseURL,"/")+"/v1/messages";body=map[string]any{"model":p.Model,"max_tokens":2048,"system":instruction,"messages":[]map[string]string{{"role":"user","content":prompt}}};headers["x-api-key"]=key;headers["anthropic-version"]="2023-06-01";case "gemini_generate_content":endpoint=strings.TrimRight(p.BaseURL,"/")+"/models/"+p.Model+":generateContent?key="+url.QueryEscape(key);body=map[string]any{"systemInstruction":map[string]any{"parts":[]map[string]string{{"text":instruction}}},"contents":[]map[string]any{{"parts":[]map[string]string{{"text":prompt}}}}};default:return "",fmt.Errorf("unsupported provider kind %q",p.Kind)};encoded,_:=json.Marshal(body);request,err:=http.NewRequestWithContext(ctx,http.MethodPost,endpoint,bytes.NewReader(encoded));if err!=nil{return "",err};request.Header.Set("Content-Type","application/json");for k,v:=range headers{request.Header.Set(k,v)};response,err:=client.Do(request);if err!=nil{return "",err};defer response.Body.Close();raw,err:=io.ReadAll(io.LimitReader(response.Body,4<<20));if err!=nil{return "",err};if response.StatusCode<200||response.StatusCode>299{return "",fmt.Errorf("provider status %d",response.StatusCode)};var payload map[string]any;if err:=json.Unmarshal(raw,&payload);err!=nil{return "",err};if text,ok:=payload["output_text"].(string);ok{return text,nil};if choices,ok:=payload["choices"].([]any);ok&&len(choices)>0{choice,_:=choices[0].(map[string]any);message,_:=choice["message"].(map[string]any);if text,ok:=message["content"].(string);ok{return text,nil}};if content,ok:=payload["content"].([]any);ok&&len(content)>0{item,_:=content[0].(map[string]any);if text,ok:=item["text"].(string);ok{return text,nil}};if candidates,ok:=payload["candidates"].([]any);ok&&len(candidates)>0{candidate,_:=candidates[0].(map[string]any);content,_:=candidate["content"].(map[string]any);parts,_:=content["parts"].([]any);if len(parts)>0{part,_:=parts[0].(map[string]any);if text,ok:=part["text"].(string);ok{return text,nil}}};return "",errors.New("provider response has no text")}
func extractObject(value string)[]byte{start:=strings.Index(value,"{");end:=strings.LastIndex(value,"}");if start<0||end<start{return nil};return []byte(value[start:end+1])}
func contains(values []string,value string)bool{for _,item:=range values{if item==value{return true}};return false}
func array(value any)[]any{values,_:=value.([]any);return values}
func safePath(path string)bool{return path!=""&&!filepath.IsAbs(path)&&!strings.Contains(path,"..")}
func allowedHost(host string,allowed []string)bool{for _,item:=range allowed{if strings.EqualFold(strings.TrimSpace(item),host){return true}};return false}
func mutation(statement string)bool{upper:=strings.ToUpper(strings.TrimSpace(statement));if strings.Contains(upper,";"){return false};return strings.HasPrefix(upper,"INSERT ")||strings.HasPrefix(upper,"UPDATE ")||strings.HasPrefix(upper,"DELETE ")}
func newID()string{raw:=make([]byte,16);_,_=rand.Read(raw);return hex.EncodeToString(raw)}
func decode(r *http.Request,dst any)error{decoder:=json.NewDecoder(io.LimitReader(r.Body,1<<20));decoder.DisallowUnknownFields();if err:=decoder.Decode(dst);err!=nil{return err};if err:=decoder.Decode(&struct{}{});err!=io.EOF{return errors.New("request must contain one JSON object")};return nil}
func writeJSON(w http.ResponseWriter,status int,value any){w.Header().Set("Content-Type","application/json");w.WriteHeader(status);_ = json.NewEncoder(w).Encode(value)}
func writeError(w http.ResponseWriter,status int,err error){writeJSON(w,status,map[string]string{"error":err.Error()})}
`
