package engine

import (
	"fmt"
	"path/filepath"

	"github.com/gongahkia/norbot/internal/domain"
	"github.com/gongahkia/norbot/internal/runtime"
)

func generateApp(workspace runtime.Workspace, run domain.Run) ([]string, error) {
	files := map[string]string{
		"generated-app/README.md": fmt.Sprintf("# Generated by Norbot\n\nRun: `%s`\nProfile: `%s`\n\nThis project was generated from an operator-approved graph.\n", run.ID, run.Profile),
		"generated-app/frontend/package.json": `{"name":"norbot-generated-frontend","private":true,"scripts":{"dev":"vite --host 0.0.0.0","build":"vite build"},"dependencies":{"@vitejs/plugin-react":"latest","vite":"latest","react":"latest","react-dom":"latest"},"devDependencies":{}}`,
		"generated-app/frontend/index.html": `<div id="root"></div><script type="module" src="/src/main.jsx"></script>`,
		"generated-app/frontend/src/main.jsx": `import {createRoot} from "react-dom/client"; import React from "react"; import "./style.css"; const App=()=> <main><h1>Norbot generated app</h1><p>Operator-approved app scaffold.</p></main>; createRoot(document.getElementById("root")).render(<App/>);`,
		"generated-app/frontend/src/style.css": `:root{font-family:ui-sans-serif,system-ui;color:#172033;background:#f7f8fb}body{margin:0}main{max-width:48rem;margin:4rem auto;padding:2rem;background:#fff;border:1px solid #dce1ea;border-radius:.5rem}h1{margin-top:0}`,
		"generated-app/frontend/Dockerfile": "FROM node:22-alpine AS build\nWORKDIR /app\nCOPY package.json .\nRUN npm install\nCOPY . .\nRUN npm run build\nFROM nginx:1.27-alpine\nCOPY --from=build /app/dist /usr/share/nginx/html\nEXPOSE 80\n",
	}
	if run.Profile != domain.ProfileFrontend {
		files["generated-app/backend/go.mod"] = "module generated/backend\n\ngo 1.26.0\n"
		files["generated-app/backend/main.go"] = `package main
import("fmt";"log";"net/http";"os")
func main(){http.HandleFunc("/api/health",func(w http.ResponseWriter,r *http.Request){w.Header().Set("content-type","application/json");fmt.Fprint(w,`+"`{\"status\":\"ok\"}`"+`)});port:=os.Getenv("PORT");if port==""{port="8000"};log.Fatal(http.ListenAndServe(":"+port,nil))}`
		files["generated-app/backend/Dockerfile"] = "FROM golang:1.26-alpine AS build\nWORKDIR /app\nCOPY . .\nRUN go build -o server .\nFROM alpine:3.21\nCOPY --from=build /app/server /server\nEXPOSE 8000\nCMD [\"/server\"]\n"
		files["generated-app/docker-compose.yml"] = `services:
  frontend:
    build: ./frontend
    ports: ["${NORBOT_PUBLIC_PORT}:80"]
  backend:
    build: ./backend
    environment: ["PORT=8000"]
`
	} else {
		files["generated-app/docker-compose.yml"] = `services:
  frontend:
    build: ./frontend
    ports: ["${NORBOT_PUBLIC_PORT}:80"]
`
	}
	if run.Profile == domain.ProfileAgentic {
		files["generated-app/backend/harness.go"] = agentHarnessSource
		files["generated-app/backend/APPROVALS.md"] = "# App-local action approvals\n\nConsequential tool invocations enter this app's persistent approval queue. The app operator approves or rejects each action before execution. Norbot does not broker runtime tool approvals.\n"
	}
	paths := make([]string, 0, len(files))
	for relative, content := range files {
		if _, err := workspace.WriteArtifact(run.ID, relative, []byte(content)); err != nil { return nil, err }
		paths = append(paths, filepath.ToSlash(relative))
	}
	return paths, nil
}

const agentHarnessSource = `package main

// ToolSpec is a typed, policy-gated app capability.
type ToolSpec struct { Name string; Kind string; ApprovalRequired bool }
// Approval is persisted by the generated app before a consequential tool call.
type Approval struct { ID string; Tool string; Input string; Status string }
// Registry exposes only tools approved by the generated app's policy.
type Registry struct { Tools map[string]ToolSpec }
func (r Registry) Allowed(name string) bool { _, ok := r.Tools[name]; return ok }
`
