package engine

import (
	_ "embed"
	"encoding/json"
	"fmt"
	"path/filepath"

	"github.com/gongahkia/norbot/internal/config"
	"github.com/gongahkia/norbot/internal/domain"
	"github.com/gongahkia/norbot/internal/runtime"
)

//go:embed assets/frontend/package-lock.json
var frontendLockfile string

func generateApp(workspace runtime.ArtifactWorkspace, run domain.Run, _ map[string]config.ToolPolicy) ([]string, error) {
	acceptance, err := json.MarshalIndent(run.Architecture.Acceptance, "", "  ")
	if err != nil {
		return nil, fmt.Errorf("encode acceptance contract: %w", err)
	}
	files := map[string]string{
		"generated-app/README.md":                           fmt.Sprintf("# Generated by Norbot\n\nRun: `%s`\nProfile: `%s`\n\nThis project was generated from an operator-approved graph.\n", run.ID, run.Profile),
		"generated-app/frontend/package.json":               `{"name":"generated-frontend","private":true,"version":"0.1.0","scripts":{"dev":"vite --host 0.0.0.0","build":"vite build","test":"node --test tests/*.test.mjs"},"dependencies":{"@vitejs/plugin-react":"6.0.4","vite":"8.1.5","react":"19.2.8","react-dom":"19.2.8"},"devDependencies":{}}`,
		"generated-app/frontend/index.html":                 `<!doctype html><html lang="en"><head><meta charset="UTF-8"/><meta name="viewport" content="width=device-width,initial-scale=1.0"/><title>Norbot generated app</title></head><body><div id="root"></div><script type="module" src="/src/main.jsx"></script></body></html>`,
		"generated-app/frontend/src/main.jsx":               `import {createRoot} from "react-dom/client";import React from "react";import "./style.css";const App=()=> <main><h1>Norbot generated app</h1><p>Operator-approved app scaffold.</p></main>;createRoot(document.getElementById("root")).render(<App/>);`,
		"generated-app/frontend/src/style.css":              `:root{font-family:ui-sans-serif,system-ui;color:#172033;background:#f7f8fb}body{margin:0}main{max-width:48rem;margin:4rem auto;padding:2rem;background:#fff;border:1px solid #dce1ea;border-radius:.5rem}h1{margin-top:0}`,
		"generated-app/frontend/tests/app.test.mjs":         `import test from "node:test";import assert from "node:assert/strict";test("generated app contract",()=>assert.equal("Norbot".length,6));`,
		"generated-app/frontend/package-lock.json":          frontendLockfile,
		"generated-app/.norbot/acceptance/contract.json":    string(acceptance),
		"generated-app/kubernetes/README.md":                "# Kubernetes artifacts\n\nNorbot applies equivalent client-go resources at deployment time.\n",
		"generated-app/kubernetes/kustomization.yaml":       "apiVersion: kustomize.config.k8s.io/v1beta1\nkind: Kustomization\nresources:\n- frontend-deployment.yaml\n- frontend-service.yaml\n",
		"generated-app/kubernetes/frontend-deployment.yaml": "apiVersion: apps/v1\nkind: Deployment\nmetadata:\n  name: generated-frontend\nspec:\n  replicas: 1\n  selector:\n    matchLabels:\n      app: generated-frontend\n  template:\n    metadata:\n      labels:\n        app: generated-frontend\n    spec:\n      containers:\n      - name: frontend\n        image: REPLACE_WITH_FRONTEND_IMAGE\n        ports:\n        - containerPort: 80\n        readinessProbe:\n          httpGet: {path: /, port: 80}\n",
		"generated-app/kubernetes/frontend-service.yaml":    "apiVersion: v1\nkind: Service\nmetadata:\n  name: generated-frontend\nspec:\n  type: ClusterIP\n  selector:\n    app: generated-frontend\n  ports:\n  - port: 80\n    targetPort: 80\n",
	}
	if run.Profile == domain.ProfileFrontend {
		return writeGeneratedFiles(workspace, run.ID, files)
	}
	files["generated-app/backend/go.mod"] = "module generated/backend\n\ngo 1.26.0\n"
	files["generated-app/backend/go.sum"] = ""
	files["generated-app/backend/main.go"] = `package main
import("fmt";"log";"net/http";"os")
func main(){http.HandleFunc("/api/health",func(w http.ResponseWriter,r *http.Request){w.Header().Set("content-type","application/json");fmt.Fprint(w,` + "`{\"status\":\"ok\"}`" + `)});port:=os.Getenv("PORT");if port==""{port="8000"};log.Fatal(http.ListenAndServe(":"+port,nil))}`
	files["generated-app/kubernetes/backend-deployment.yaml"] = "apiVersion: apps/v1\nkind: Deployment\nmetadata:\n  name: generated-backend\nspec:\n  replicas: 1\n  selector:\n    matchLabels:\n      app: generated-backend\n  template:\n    metadata:\n      labels:\n        app: generated-backend\n    spec:\n      containers:\n      - name: backend\n        image: REPLACE_WITH_BACKEND_IMAGE\n        ports:\n        - containerPort: 8000\n        readinessProbe:\n          httpGet: {path: /api/health, port: 8000}\n"
	files["generated-app/kubernetes/backend-service.yaml"] = "apiVersion: v1\nkind: Service\nmetadata:\n  name: generated-backend\nspec:\n  type: ClusterIP\n  selector:\n    app: generated-backend\n  ports:\n  - port: 8000\n    targetPort: 8000\n"
	files["generated-app/kubernetes/kustomization.yaml"] += "- backend-deployment.yaml\n- backend-service.yaml\n"
	if run.Profile == domain.ProfileAgentic {
		files["generated-app/backend/AGENT_RUNTIME.md"] = "# Norbot control-plane agent runtime\n\nProvider calls, tool policy, approvals, sandbox execution, session state, and audit records are owned by Norbot. This deployed application receives no model credential and exposes no local tool executor.\n"
	}
	return writeGeneratedFiles(workspace, run.ID, files)
}

func writeGeneratedFiles(workspace runtime.ArtifactWorkspace, runID string, files map[string]string) ([]string, error) {
	paths := make([]string, 0, len(files))
	for relative, content := range files {
		if _, err := workspace.WriteArtifact(runID, relative, []byte(content)); err != nil {
			return nil, err
		}
		paths = append(paths, filepath.ToSlash(relative))
	}
	return paths, nil
}
