receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318
  prometheus:
    config:
      scrape_configs:
        - job_name: norbot
          static_configs:
            - targets: ["norbot:8080"]
exporters:
  debug:
    verbosity: basic
  otlphttp/jaeger:
    endpoint: http://jaeger:4318
  prometheus:
    endpoint: "0.0.0.0:8889"
service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [debug, otlphttp/jaeger]
    metrics:
      receivers: [prometheus]
      exporters: [debug, prometheus]
