package cmd

import (
	"fmt"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"sort"
	"strconv"
	"strings"
	"time"

	"github.com/gongahkia/paw/internal/budget"
)

type benchRow struct {
	RunID             string
	Commit            string
	Config            string
	ConfigPath        string
	Dataset           string
	BrainModel        string
	DroneModel        string
	Hardware          string
	Date              string
	Tasks             int
	PassRate          string
	BrainInputTokens  string
	BrainOutputTokens string
	BrainTokenSource  string
	DroneTokens       string
	DroneTokenSource  string
	WallSeconds       string
	TraceBundle       string
}

func (s benchSummary) row(config string, opts benchOptions) benchRow {
	runID := opts.JobName
	return benchRow{
		RunID:             runID,
		Commit:            currentCommit(),
		Config:            config,
		ConfigPath:        filepath.ToSlash(filepath.Join("results-configs", runID+".toml")),
		Dataset:           opts.Dataset,
		BrainModel:        envModel("PAW_BRAIN_", opts.Model),
		DroneModel:        droneModel(config),
		Hardware:          hardwareLabel(),
		Date:              time.Now().UTC().Format("2006-01-02"),
		Tasks:             s.Tasks,
		PassRate:          ratio(s.Passed, s.Tasks),
		BrainInputTokens:  formatMedian(s.BrainInputTokens, 0),
		BrainOutputTokens: formatMedian(s.BrainOutputTokens, 0),
		BrainTokenSource:  normalizedBenchTokenSource(s.BrainTokenSource),
		DroneTokens:       formatMedian(s.DroneTokens, 0),
		DroneTokenSource:  normalizedBenchTokenSource(s.DroneTokenSource),
		WallSeconds:       formatMedian(s.WallSeconds, 1),
		TraceBundle:       filepath.ToSlash(filepath.Join(opts.JobsDir, runID)),
	}
}

func printBenchTable(w io.Writer, rows []benchRow) error {
	if _, err := fmt.Fprintln(w, "| config | tasks | pass@1 | brain_in_tok/task (median) | brain_out_tok/task (median) | drone_tok/task | wall_s/task |"); err != nil {
		return err
	}
	if _, err := fmt.Fprintln(w, "| --- | ---: | ---: | ---: | ---: | ---: | ---: |"); err != nil {
		return err
	}
	for _, row := range rows {
		if _, err := fmt.Fprintln(w, row.markdown()); err != nil {
			return err
		}
	}
	return nil
}

const (
	resultsStartMarker = "<!-- paw-results:start -->"
	resultsEndMarker   = "<!-- paw-results:end -->"
)

func updateResultsFile(path string, row benchRow) error {
	data, err := os.ReadFile(path)
	if err != nil {
		return err
	}
	lines := strings.Split(string(data), "\n")
	start, end := markerBounds(lines)
	if start == -1 || end == -1 || start >= end {
		return fmt.Errorf("results table markers not found in %s", path)
	}
	next := row.resultsMarkdown()
	replaceIndex := -1
	placeholderIndex := -1
	for i := start + 1; i < end; i++ {
		if resultRowRunID(lines[i]) == row.RunID {
			replaceIndex = i
			break
		}
		if placeholderIndex == -1 && resultPlaceholderRowMatches(lines[i], row.Config) {
			placeholderIndex = i
		}
	}
	if replaceIndex == -1 {
		replaceIndex = placeholderIndex
	}
	if replaceIndex >= 0 {
		lines[replaceIndex] = next
	} else {
		lines = append(lines[:end], append([]string{next}, lines[end:]...)...)
	}
	out := strings.Join(lines, "\n")
	return os.WriteFile(path, []byte(out), 0o644)
}

func markerBounds(lines []string) (int, int) {
	start, end := -1, -1
	for i, line := range lines {
		switch strings.TrimSpace(line) {
		case resultsStartMarker:
			start = i
		case resultsEndMarker:
			end = i
			return start, end
		}
	}
	return start, end
}

func (r benchRow) markdown() string {
	return fmt.Sprintf("| %s | %d | %s | %s | %s | %s | %s |", r.Config, r.Tasks, r.PassRate, r.BrainInputTokens, r.BrainOutputTokens, r.DroneTokens, r.WallSeconds)
}

func (r benchRow) resultsMarkdown() string {
	config := r.Config
	if r.ConfigPath != "" {
		config = fmt.Sprintf("[%s](%s)", r.Config, r.ConfigPath)
	}
	return fmt.Sprintf("| %s | %s | %s | %s | %s | %s | %s | %s | %d | %s | %s | %s | %s | %s | %s |",
		r.RunID,
		r.Commit,
		config,
		r.Dataset,
		r.BrainModel,
		r.DroneModel,
		r.Hardware,
		r.Date,
		r.Tasks,
		r.WallSeconds,
		r.BrainInputTokens,
		r.BrainOutputTokens,
		r.DroneTokens,
		r.PassRate,
		r.TraceBundle,
	)
}

func resultRowMatches(line, config string) bool {
	return strings.HasPrefix(line, "| "+config+" |") || strings.Contains(line, "| ["+config+"](")
}

func resultPlaceholderRowMatches(line, config string) bool {
	return resultRowMatches(line, config) && strings.Contains(line, "| TBD |")
}

func resultRowRunID(line string) string {
	fields := strings.Split(line, "|")
	if len(fields) < 3 {
		return ""
	}
	return strings.TrimSpace(fields[1])
}

func writeBenchResultConfig(resultsPath string, row benchRow, opts benchOptions) error {
	if row.ConfigPath == "" {
		return nil
	}
	path := filepath.Join(filepath.Dir(resultsPath), filepath.FromSlash(row.ConfigPath))
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	content := strings.Join([]string{
		"# generated by paw bench",
		"run_id = " + tomlString(row.RunID),
		"commit = " + tomlString(row.Commit),
		"config = " + tomlString(row.Config),
		"dataset = " + tomlString(opts.Dataset),
		"model = " + tomlString(opts.Model),
		"brain_token_source = " + tomlString(row.BrainTokenSource),
		"drone_token_source = " + tomlString(row.DroneTokenSource),
		"jobs_dir = " + tomlString(opts.JobsDir),
		"job_name = " + tomlString(opts.JobName),
		"n_concurrent = " + strconv.Itoa(opts.NConcurrent),
		"n_tasks = " + strconv.Itoa(opts.NTasks),
		"n_attempts = " + strconv.Itoa(opts.NAttempts),
		"date = " + tomlString(row.Date),
		"trace_bundle = " + tomlString(row.TraceBundle),
		"trace_mode = " + tomlString(benchTraceMode()),
		"",
		"[env]",
		"PAW_BENCH_CONFIG = " + tomlString(row.Config),
		envConfigLine("PAW_BRAIN_TRANSPORT"),
		envConfigLine("PAW_BRAIN_BASE_URL"),
		envConfigLine("PAW_BRAIN_MODEL"),
		envConfigLine("PAW_DRONE_TRANSPORT"),
		envConfigLine("PAW_DRONE_BASE_URL"),
		envConfigLine("PAW_DRONE_MODEL"),
		envConfigLine("PAW_CALL_TIMEOUT"),
		envConfigLine("PAW_BENCH_HARDWARE"),
		"PAW_BRAIN_API_KEY = \"<redacted>\"",
		"PAW_DRONE_API_KEY = \"<redacted>\"",
		"",
	}, "\n")
	return os.WriteFile(path, []byte(content), 0o644)
}

func envConfigLine(key string) string {
	return key + " = " + tomlString(os.Getenv(key))
}

func tomlString(value string) string {
	encoded, err := strconv.Unquote(strconv.Quote(value))
	if err != nil {
		encoded = value
	}
	return strconv.Quote(encoded)
}

func currentCommit() string {
	out, err := exec.Command("git", "rev-parse", "HEAD").Output()
	if err != nil {
		return "unknown"
	}
	return strings.TrimSpace(string(out))
}

func hardwareLabel() string {
	if value := os.Getenv("PAW_BENCH_HARDWARE"); value != "" {
		return value
	}
	return runtime.GOOS + "/" + runtime.GOARCH
}

func envModel(prefix, fallback string) string {
	model := os.Getenv(prefix + "MODEL")
	transport := os.Getenv(prefix + "TRANSPORT")
	if model == "" {
		return fallback
	}
	if transport == "" {
		return model
	}
	return transport + "/" + model
}

func droneModel(config string) string {
	if config == "raw" || config == "no-compress" {
		return "n/a"
	}
	return envModel("PAW_DRONE_", "n/a")
}

func ratio(numerator, denominator int) string {
	if denominator == 0 {
		return "n/a"
	}
	return fmt.Sprintf("%.2f", float64(numerator)/float64(denominator))
}

func formatMedian(values []float64, decimals int) string {
	if len(values) == 0 {
		return "n/a"
	}
	sorted := append([]float64(nil), values...)
	sort.Float64s(sorted)
	mid := len(sorted) / 2
	value := sorted[mid]
	if len(sorted)%2 == 0 {
		value = (sorted[mid-1] + sorted[mid]) / 2
	}
	return fmt.Sprintf("%."+strconv.Itoa(decimals)+"f", value)
}

func normalizedBenchTokenSource(source string) string {
	return budget.NormalizeTokenSource(source)
}
